server:
  port: 8017
spring:
  application:
    name: jdck-information-data-sync
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
      url: jdbc:sqlserver://39.104.184.19:1433;DatabaseName=DB_DZGL_SX
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: jdck+123456
  jpa:
    database: sql_server
    show-sql: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  rabbitmq:
    mq1:
      host:  39.104.184.19
      port:  5672
      username: jdck
      password: jdck@123456
    listener:
      queues: SY-000001,LT-000001,LG-000001
  logging:
    congfig: classpath:logback-spring.xml
    path: D:/jdck/information-sync-logs